# Generated by Django 4.0 on 2022-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('chapters', models.IntegerField()),
            ],
        ),
    ]
